name: build
on: 
  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           fetch-depth: 0
           token: ${{ secrets.DOCKER_GIT_TOKEN }}

      - name: build-and-push
        run: |
          echo "hello"
